### ISSUE TITLE
Flickering in 0.28

### ISSUE THREAD

**Issue by ethereumdegen** [vladbat00/bevy_egui#295] opened 2024-07-15 22:25 UTC
Updated this dependency  to 0.28.0 and now my fork of PLS editor has flickering on the egui windows

**Comment by mvlabat** [comment] 2024-07-17 10:32
Hi. Could you help me with a minimal reproducible example with just using `bevy_egui`? So we can rule out issues on the PLS editor end.

**Comment by vladbat00** [comment] 2024-12-01 12:51
I'll close the issue since I haven't got a response. But if the issue is still actual, feel free to comment/reopen.

**Closed by vladbat00** 2024-12-01 12:51 UTC
