### ISSUE TITLE
update rustdoc to readme

### ISSUE THREAD

**Issue by mirsella** [vladbat00/bevy_egui#330] opened 2024-12-05 07:45 UTC
https://vladbat00.github.io/bevy_egui_web_showcase/index.html gives a 404

**Comment by vladbat00** [comment] 2024-12-06 12:25
Hm, I can't reproduce it. I changed my nickname not so long ago, the previous link was https://mvlabat.github.io/bevy_egui_web_showcase/index.html, which is now 404. Where I forgot to update the link though is https://github.com/vladbat00/bevy_egui/blob/581a0e1b423e3fae4d3a011c08c8d8000702b544/src/lib.rs. And it's not the only inconsistency with the current readme file... Maybe you were checking the link from docs.rs (which reads the contents from `src/lib.rs`)?

**Comment by mirsella** [comment] 2024-12-06 13:13
ohhh yes thats it

**Comment by vladbat00** [comment] 2024-12-21 22:41
Fixed in #333, thanks

**Closed by vladbat00** 2024-12-21 22:41 UTC
